### PR TITLE
Add missing svg icons 

### PR DESCRIPTION
**Pull request by adambelis**
image
This adds 5  new SVG icons .
they are on 16x16 grid we will see how wharp they render maybe we will need to go back to 10x10 if it erns out  blurry .
i did not create 2 icons from this set since they are the same as fill and stroke and should be reused 

Svgs are create with white color + alfa probably hard to see in current previes. not sure ho will qt render this

### CODE REVIEW

**Comment by adambelis** [comment]
not sure if this is right workflow . (forking and pushing with new changes) a;also not sure if this is right aproche for now i just added svgs to same folder and dtit nothing else so no fucnional changes

**Comment by rodlie** [comment]
> not sure if this is right workflow . (forking and pushing with new changes)

for now ok.

> also not sure if this is right aproche for now i just added svgs to same folder and dtit nothing else so no fucnional changes

Not important, I will renamed/move if needed.

---

* The icons with gradient should probably have a border around them?
* The graph icon should have a frame, since we add a background color when active?

**Comment by adambelis** [comment]
perosnaly i prefer look  without borders for all 3 icons  but if you really want it i can add it . . maybe we can test how it look in UI and add it later if needed ? I'mho it should work even without

**Comment by rodlie** [comment]
It's ok for the gradient icons, but the graph icon should have a border/frame since we fill the background with a random color. If not it might look odd.

But let's merge and test this anyway, it's easy to make adjustments.

**Pull request merged**
