### PR TITLE
Updated lock and unlock icons

### PR DESCRIPTION
**Pull request by pgilfernandez**
I think these icons needed some work as both states showed a "closed padlock"...
Here is my proposal (I didn't used the red color as I think it is too intrusive and it doesn't strictly follow the Blender style):

timeline

### CODE REVIEW

**Comment by rodlie** [comment]
Thanks, will need to test how they work in "real life", as icons without fill (usually) don't look good when they get too small.

**Comment by pgilfernandez** [comment]
In case it doesn't work we can always use a filled one, lock opened and maybe with some transparency to make it "less important". Something like:

unlocked

**Comment by rodlie** [comment]
Screenshot:
Screenshot from 2024-10-30 15-19-51

A bit unsure...

**Comment by pgilfernandez** [comment]
Umm, I still this option better:

lock

**Comment by rodlie** [comment]
That was a screenshot from this PR, I think you committed the wrong unlock icon.

**Comment by pgilfernandez** [comment]
let me check...

**Comment by pgilfernandez** [comment]
I left it yesterday mid finished: I don't know what happened but you were right, the uploaded file had fill... I have updated it with the one the right one, now it is double checked, hehehe.

Let me know if you find this one better.

**Comment by rodlie** [comment]
Thanks, will test after work.

**Pull request merged**
