### PR TITLE
Update audio layer icons for muted and unmuted states

### PR DESCRIPTION
**Pull request by pgilfernandez**
Old ones didn't follow the Blender icon system and used a red line to represent the muted state...

muted_unmuted

### CODE REVIEW

**Comment by rodlie** [comment]
Thanks.

Been thinking about replacing them for a while, but always forget :smile:

**Comment by rodlie** [comment]
Icon sizes differ, not good:
Screenshot from 2024-11-24 00-37-34

**Comment by pgilfernandez** [comment]
Oh, I just got the Blender ones and edit the muted one... I didn't pay attention to it or test them on app, sorry about it.

Tomorrow I will update them, it's not big deal.

**Comment by rodlie** [comment]
No problem :+1:

**Comment by rodlie** [comment]
Fixed in https://github.com/friction2d/friction-icon-theme/commit/65713ae03ed6a8997e035ba3f871bace55f753d4 + https://github.com/friction2d/friction-icon-theme/commit/2b166a183f82c18fd5fa7290ad8161981b58d781

**Pull request merged**
