### PR TITLE
Update  checkboxes icons

### PR DESCRIPTION
**Pull request by pgilfernandez**
I feel like your actual icons are elegant but they are prone to confuse new users as the "unchecked" state is just an X that very often means forbidden, unable...

I'm proposing something more common with Blender style, I think the result looks better:

menu

### CODE REVIEW

**Comment by rodlie** [comment]
Agree on the checkboxes, I just used what I had available at the time, note that the dialog icons are used for other things, so you will need to rename them to something else, maybe box-checked, box-unchecked or something. And I will replace the icon names in Friction to point to the new icons where needed.

**Comment by pgilfernandez** [comment]
Done

**Comment by rodlie** [comment]
Thanks :+1:

**Comment by rodlie** [comment]
Screenshot:
menu

**Pull request merged**
