### PR TITLE
Some node alignments for range icons

### PR DESCRIPTION
**Pull request by pgilfernandez**
I found some little misalignments and I wanted to fix them...

### CODE REVIEW

**Comment by rodlie** [comment]
This PR got borked by merging #18

**Comment by rodlie** [comment]
Sure

**Comment by pgilfernandez** [comment]
Argg, those new "force pushed" commits didn't resolve the conflicts... I'm fighting with Git and could not resolve this so I'm just closing this PR and creating a new one with the current `main`...

This solves the problem...

**Comment by rodlie** [comment]
Sure, just create a new PR.

**Pull request closed without merging**
